import { Product, ProductBadge } from '../types/product';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 1,
    name: "Artisan Organic Honey",
    farmer: "Mysore Apiaries",
    farmerId: "farmer-001",
    image: "/honey-jar.png",
    originalPrice: 599,
    offerPrice: 449,
    discountPercent: 25,
    stock: 12,
    category: "Pantry",
    unit: "500g jar",
    description: "Raw, unfiltered wildflower honey harvested from our apiaries in the Mysore countryside. Rich in enzymes and natural antioxidants. Our bees forage freely across 200 acres of wildflower meadows, producing honey that retains all its natural goodness.",
    farmerLocation: "H.D. Kote, Mysore",
    farmerSince: "2018",
    farmingMethod: "Natural Beekeeping",
    certifications: ["Organic India", "FSSAI"],
    harvestDate: "2026-03-28",
    shelfLife: "24 months",
    badges: ["bestseller", "featured"] as ProductBadge[],
    rating: 4.8,
    reviewCount: 127,
  },
  {
    id: 2,
    name: "Heirloom Tomatoes",
    farmer: "Green Valley Fields",
    farmerId: "farmer-002",
    image: "/tomatoes-basket.png",
    originalPrice: 120,
    offerPrice: 89,
    discountPercent: 26,
    stock: 45,
    category: "Vegetables",
    unit: "1 kg",
    description: "Vine-ripened heirloom tomatoes grown without pesticides. Perfect for salads, sauces, and everyday cooking. These heritage variety tomatoes have been cultivated from seeds passed down through three generations of the Gowda family.",
    farmerLocation: "Mysore, Karnataka",
    farmerSince: "2015",
    farmingMethod: "Organic Polyculture",
    certifications: ["PGS-India Organic"],
    harvestDate: "2026-04-03",
    shelfLife: "5-7 days",
    badges: ["just_harvested", "seasonal"] as ProductBadge[],
    rating: 4.6,
    reviewCount: 89,
  },
  {
    id: 3,
    name: "Farm Fresh Eggs",
    farmer: "Mysore Co-op",
    farmerId: "farmer-003",
    image: "/eggs-carton.png",
    originalPrice: 180,
    offerPrice: 149,
    discountPercent: 17,
    stock: 30,
    category: "Dairy & Eggs",
    unit: "12 pcs",
    description: "Free-range eggs from pasture-raised hens. Rich golden yolks packed with omega-3 fatty acids. Our hens roam freely in open pastures, feeding on a natural diet of insects, greens, and organic feed.",
    farmerLocation: "Nanjangud, Karnataka",
    farmerSince: "2020",
    farmingMethod: "Free-Range Pasture",
    certifications: ["FSSAI", "Animal Welfare Certified"],
    harvestDate: "2026-04-04",
    shelfLife: "14 days",
    badges: ["just_harvested", "bestseller"] as ProductBadge[],
    rating: 4.7,
    reviewCount: 203,
  },
  {
    id: 4,
    name: "Organic Jaggery",
    farmer: "Nanjangud Farms",
    farmerId: "farmer-004",
    image: "/jaggery.png",
    originalPrice: 250,
    offerPrice: 199,
    discountPercent: 20,
    stock: 8,
    category: "Pantry",
    unit: "500g block",
    description: "Traditional sugarcane jaggery made using age-old methods. A healthier alternative to refined sugar. Each block is hand-pressed from freshly crushed sugarcane juice, cooked in traditional iron kadhai over wood fire.",
    farmerLocation: "T. Narasipura, Karnataka",
    farmerSince: "2012",
    farmingMethod: "Traditional Organic",
    certifications: ["NPOP Organic", "FSSAI"],
    harvestDate: "2026-03-15",
    shelfLife: "12 months",
    badges: ["seasonal"] as ProductBadge[],
    rating: 4.5,
    reviewCount: 56,
  },
  {
    id: 5,
    name: "Cold-Pressed Coconut Oil",
    farmer: "Chamundi Agro",
    farmerId: "farmer-005",
    image: "/coconut-oil.png",
    originalPrice: 450,
    offerPrice: 379,
    discountPercent: 16,
    stock: 3,
    category: "Pantry",
    unit: "500ml bottle",
    description: "Virgin coconut oil extracted using traditional wood-pressed methods. Ideal for cooking, skincare, and hair care. We process freshly harvested coconuts within 24 hours to retain maximum nutrients and aroma.",
    farmerLocation: "Nanjangud, Karnataka",
    farmerSince: "2016",
    farmingMethod: "Wood-Pressed Traditional",
    certifications: ["Organic India", "FSSAI"],
    harvestDate: "2026-03-20",
    shelfLife: "18 months",
    badges: ["featured"] as ProductBadge[],
    rating: 4.9,
    reviewCount: 178,
  },
  {
    id: 6,
    name: "Organic Turmeric Powder",
    farmer: "Spice Route Farms",
    farmerId: "farmer-006",
    image: "/turmeric.png",
    originalPrice: 320,
    offerPrice: 249,
    discountPercent: 22,
    stock: 18,
    category: "Spices",
    unit: "250g pouch",
    description: "High-curcumin turmeric powder from organically grown roots. Vibrant color and strong aroma. Our turmeric is grown in the mineral-rich red soil of Mysore's highlands, sun-dried, and stone-ground to preserve its potency.",
    farmerLocation: "Mysore, Karnataka",
    farmerSince: "2014",
    farmingMethod: "Regenerative Organic",
    certifications: ["NPOP Organic", "Spices Board India"],
    harvestDate: "2026-02-10",
    shelfLife: "24 months",
    badges: ["bestseller", "new"] as ProductBadge[],
    rating: 4.7,
    reviewCount: 142,
  },
];
